name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  mobx: ^2.3.0
  mobx_codegen: ^2.6.0
  build_runner: ^2.4.7
  intl: ^0.19.0
  url_launcher: ^6.2.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  http: ^1.1.2
  flutter_mobx: ^2.2.0+1
  easy_image_viewer: ^1.4.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2
  firebase_messaging: ^14.8.0
  flutter_local_notifications: ^17.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.png"
  min_sdk_android: 21